### ISSUE TITLE
Add a roadmap page in the o3de.org/docs

### ISSUE THREAD

**Issue by vincent6767** [o3de/sig-docs-community#102]
Hi docs-community CC: @chanmosq @aFinchy 
Thanks for creating a roadmap as part of this RFC: https://github.com/o3de/sig-release/issues/79. Really appreciate it! 

Since we have a few roadmaps already, I would like to get your thoughts regarding having SIG roadmap links in the docs websites. 

# Objective
1. To increase community awareness of the roadmap.

# Content
1. The page contains all roadmap links.
2. The page contains a disclaimer the roadmap is subject to change as the maintainer considers feedback both from the community and others.

# Location
1. The page is located at the o3de.org/docs/roadmap
2. The page can be accessed from the navigation menu.

# Why on O3DE Docs website?
I propose the roadmap in the o3de.org/docs as I imagine community members who read the docs will wonder what's next for the project. By having the roadmap in the docs websites, we can address the community needs without them navigating into other parts of the O3DE websites.

CC: @tonybalandiuk

**Comment by chanmosq** [comment]
Hey @vincent6767, thanks for bringing this up! It's very important to get some visibility on the new roadmaps. 

I think the main "Roadmaps" link should live somewhere in the home page of o3de.org. The concept of a roadmap is adjacent to docs, but serves it's own purpose. Hypothetically, if someone was reading the docs and thought "I wonder what else is on their roadmap?", I think they would look for the roadmap in the main o3de.org homepage instead of o3de.org/docs, which is understood to be a place for documentation about the product.

In fact, it seems like having "Roadmaps" on the home page is part of the [website development plan](https://www.figma.com/file/LCRhOYaja2UqTPlxon5O0N/O3DE_Website?node-id=0%3A1&t=qA2TC98AbEi5khIl-0).

![image](https://user-images.githubusercontent.com/75444793/218546934-dd7c1ae9-6fe4-4b9e-a5e3-7a2270f4e4ee.png)


However, there is a place in the docs where a link to the roadmaps would be appropriate: the [Contributing guide](https://www.o3de.org/docs/contributing/).

**Comment by chanmosq** [comment]
We've discussed this issue at the sig-docs-community meeting. We propose resolving this issue with the following steps:
**1. Update the Contributing Guide (o3de.org/docs/contributing/)**:
Create a new page that lists each SIG, a brief description of each, and a link to their roadmap.
  - The description of the SIG should include the key features they support.
  - It may make sense to format this as a table: SIG, Description, Roadmap.
  - Page title suggestion: "SIG Roadmaps"
  - Add a brief introductory paragraph

**2. Update the Contribute section on the home page (o3de.org/contributing)**:
  - Add respective links to the (above) Contributing Guide. The purpose of this page is to be a minimal landing page regarding contributing to O3DE.

@vincent6767 Let me know your thoughts!

**Comment by vincent6767** [comment]
Hi @chanmosq Thanks for sharing your thoughts around this! I'll review this weekend and comment.

**Comment by vincent6767** [comment]
@chanmosq In case you miss the notification ^

**Comment by chanmosq** [comment]
@vincent6767 Thanks for reviewing! Apologies I did miss the notification - 

1. The sig-docs-community can be responsible for doing 1) and 2). I'll create tickets and link them here.
2. When a PR is created to update the o3de.org/contributing page, I'll make sure someone from the Marketing team reviews it. Given that the change is minor - just one sentence linking to the O3DE contributing page - I don't think there's much else to discuss. Though if there is, someone can speak to it via the PR. 
3. The [o3de.org/docs/contributing](https://www.o3de.org/docs/contributing/) page refers to the O3DE Contributing Guide, not the contributing section of the home page. 
4. The meta roadmap is an idea that's still surfacing, no plans around it yet. The primary discussions are happening with Marketing team and @thoraxe. If you have additional thoughts around having a meta roadmap, feel free to leave comments under the [meeting notes](https://github.com/o3de/sig-docs-community/issues/98), and talk to those folks.

**Comment by vincent6767** [comment]
Thanks for the response @chanmosq !
Seems all of the items mentioned are going to be handled by SIG-docs-community. Is there anything that the SIG release can help with?

**Comment by vincent6767** [comment]
@chanmosq In case you miss the notification. All of the action items look good to me. What are the next action items and is there anything that SIG release can help?

**Comment by chanmosq** [comment]
@vincent6767 Thanks for following up. I think we have what we need at this time, but I'll let you know if something comes up!

**Comment by chanmosq** [comment]
Closing - A new ticket was opened in o3de.org repo with the solution discussed here
